import 'package:flutter/material.dart';

import 'package:catrans_app/core/network/api_exception.dart';
import 'package:catrans_app/models/staff/admin/transport/admin_counter_models.dart';
import 'package:catrans_app/models/staff/structured_api_error.dart';
import 'package:catrans_app/screens/staff/admin/transport/shared/admin_transport_status_badge.dart';
import 'package:catrans_app/widgets/staff/staff_error_state.dart';
import 'package:catrans_app/widgets/staff/staff_loading_state.dart';

Future<void> showAdminCounterDetailDialog({required BuildContext context, required AdminStationCounter counter, required Future<AdminStationCounter> Function(String id) loadDetail}) => showDialog<void>(context: context, useSafeArea: true, builder: (dialogContext) { final size = MediaQuery.sizeOf(dialogContext); final content = AdminCounterDetailDialog(key: Key('admin-counter-details-${counter.id}'), counter: counter, loadDetail: loadDetail); if (size.width < 640) return Dialog.fullscreen(child: SafeArea(child: content)); return Dialog(clipBehavior: Clip.antiAlias, shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)), child: SizedBox(width: size.width > 640 ? 600 : size.width - 32, height: size.height > 560 ? 500 : size.height * 0.9, child: content)); });

class AdminCounterDetailDialog extends StatefulWidget { final AdminStationCounter counter; final Future<AdminStationCounter> Function(String id) loadDetail; const AdminCounterDetailDialog({super.key, required this.counter, required this.loadDetail}); @override State<AdminCounterDetailDialog> createState() => _AdminCounterDetailDialogState(); }
class _AdminCounterDetailDialogState extends State<AdminCounterDetailDialog> { AdminStationCounter? _detail; bool _isLoading = true; String? _error; @override void initState() { super.initState(); _load(); } Future<void> _load() async { setState(() { _isLoading = true; _error = null; }); try { final detail = await widget.loadDetail(widget.counter.id); if (!mounted) return; setState(() => _detail = detail); } catch (error) { if (!mounted) return; setState(() => _error = _messageFromError(error)); } finally { if (mounted) setState(() => _isLoading = false); } } @override Widget build(BuildContext context) { final detail = _detail ?? widget.counter; return Material(color: const Color(0xFFF5F6FA), child: Column(children: [_Header(counter: detail), Expanded(child: Padding(padding: const EdgeInsets.all(18), child: _buildBody(detail)))])); } Widget _buildBody(AdminStationCounter detail) { if (_isLoading) return const StaffLoadingState(message: 'Chargement du guichet...'); if (_error != null) return StaffErrorState(message: _error!, onRetry: _load); return SingleChildScrollView(child: _Section(title: 'Informations guichet', rows: [_Row('Code', _display(detail.code)), _Row('Libellé', _display(detail.label)), _Row('Gare', _display(detail.station.name)), _Row('Statut', detail.isActive ? 'Actif' : 'Inactif'), _Row('Créé le', _formatDate(detail.createdAt)), _Row('Mis à jour le', _formatDate(detail.updatedAt))])); } String _messageFromError(Object error) { if (error is ApiException) return StructuredApiError.fromException(error).userMessage; return 'Impossible de charger le détail guichet.'; } }
class _Header extends StatelessWidget { final AdminStationCounter counter; const _Header({required this.counter}); @override Widget build(BuildContext context) => Container(padding: const EdgeInsets.all(18), color: Colors.white, child: Row(children: [const Icon(Icons.point_of_sale, color: Color(0xFF0F056B)), const SizedBox(width: 12), Expanded(child: Text('${_display(counter.code)} · ${_display(counter.label)}', style: const TextStyle(fontWeight: FontWeight.w900, fontSize: 18))), AdminTransportStatusBadge(isActive: counter.isActive), IconButton(tooltip: 'Fermer', onPressed: () => Navigator.pop(context), icon: const Icon(Icons.close))])); }
class _Section extends StatelessWidget { final String title; final List<_Row> rows; const _Section({required this.title, required this.rows}); @override Widget build(BuildContext context) => Container(width: double.infinity, padding: const EdgeInsets.all(14), decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(8), border: Border.all(color: const Color(0xFFE4E7EF))), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(title, key: const Key('admin-counter-detail-title'), style: const TextStyle(fontWeight: FontWeight.w900)), const SizedBox(height: 10), ...rows.map((row) => Padding(padding: const EdgeInsets.only(bottom: 8), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(width: 130, child: Text(row.label, style: const TextStyle(color: Color(0xFF666A76)))), Expanded(child: Text(row.value))])))])); }
class _Row { final String label; final String value; const _Row(this.label, this.value); }
String _display(String? value) { final trimmed = value?.trim(); return trimmed == null || trimmed.isEmpty ? '-' : trimmed; }
String _formatDate(String value) { final parsed = DateTime.tryParse(value); if (parsed == null) return _display(value); final local = parsed.toLocal(); return '${local.day.toString().padLeft(2, '0')}/${local.month.toString().padLeft(2, '0')}/${local.year.toString().padLeft(4, '0')} à ${local.hour.toString().padLeft(2, '0')}:${local.minute.toString().padLeft(2, '0')}'; }
