import 'package:flutter/material.dart';

import 'package:catrans_app/models/staff/admin/transport/admin_counter_models.dart';
import 'package:catrans_app/models/staff/structured_api_error.dart';
import 'package:catrans_app/widgets/staff/staff_error_state.dart';

class AdminCounterFormResult { final AdminStationCounterCreateRequest? createRequest; final AdminStationCounterUpdateRequest? updateRequest; const AdminCounterFormResult.create(this.createRequest) : updateRequest = null; const AdminCounterFormResult.update(this.updateRequest) : createRequest = null; }

Future<AdminCounterFormResult?> showAdminCounterFormDialog({required BuildContext context, required bool isSubmitting, required String stationName, StructuredApiError? error, AdminStationCounter? initialCounter, AdminStationCounterCreateRequest? initialCreateRequest, AdminStationCounterUpdateRequest? initialUpdateRequest}) => showDialog<AdminCounterFormResult>(context: context, useSafeArea: true, barrierDismissible: !isSubmitting, builder: (dialogContext) { final size = MediaQuery.sizeOf(dialogContext); final content = AdminCounterFormDialog(isSubmitting: isSubmitting, stationName: stationName, error: error, initialCounter: initialCounter, initialCreateRequest: initialCreateRequest, initialUpdateRequest: initialUpdateRequest); if (size.width < 640) return Dialog.fullscreen(child: SafeArea(child: content)); return Dialog(clipBehavior: Clip.antiAlias, shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)), child: SizedBox(width: size.width > 560 ? 520 : size.width - 32, height: size.height > 520 ? 460 : size.height * 0.9, child: content)); });

class AdminCounterFormDialog extends StatefulWidget { final bool isSubmitting; final String stationName; final StructuredApiError? error; final AdminStationCounter? initialCounter; final AdminStationCounterCreateRequest? initialCreateRequest; final AdminStationCounterUpdateRequest? initialUpdateRequest; const AdminCounterFormDialog({super.key, required this.isSubmitting, required this.stationName, this.error, this.initialCounter, this.initialCreateRequest, this.initialUpdateRequest}); @override State<AdminCounterFormDialog> createState() => _AdminCounterFormDialogState(); }
class _AdminCounterFormDialogState extends State<AdminCounterFormDialog> { final _formKey = GlobalKey<FormState>(); late final TextEditingController _codeController; late final TextEditingController _labelController; bool get _isEdit => widget.initialCounter != null; @override void initState() { super.initState(); final c = widget.initialCounter; final create = widget.initialCreateRequest; final update = widget.initialUpdateRequest; _codeController = TextEditingController(text: create?.code ?? update?.code ?? c?.code ?? ''); _labelController = TextEditingController(text: create?.label ?? update?.label ?? c?.label ?? ''); } @override void dispose() { _codeController.dispose(); _labelController.dispose(); super.dispose(); } @override Widget build(BuildContext context) => Material(color: const Color(0xFFF5F6FA), child: Column(children: [_Header(title: _isEdit ? 'Modifier le guichet' : 'Nouveau guichet', onClose: widget.isSubmitting ? null : () => Navigator.pop(context)), Expanded(child: Form(key: _formKey, child: ListView(padding: const EdgeInsets.all(18), children: [Text('Gare : ${widget.stationName}', style: const TextStyle(fontWeight: FontWeight.w800, color: Color(0xFF0F056B))), const SizedBox(height: 12), if (widget.error != null && widget.error?.field == null) ...[StaffErrorState(message: widget.error!.userMessage), const SizedBox(height: 12)], _TextField(controller: _codeController, label: 'Code', fieldName: 'code', error: widget.error, requiredField: true, enabled: !widget.isSubmitting), const SizedBox(height: 12), _TextField(controller: _labelController, label: 'Libellé', fieldName: 'label', error: widget.error, requiredField: true, enabled: !widget.isSubmitting)]))), Container(padding: const EdgeInsets.all(16), color: Colors.white, child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [TextButton(onPressed: widget.isSubmitting ? null : () => Navigator.pop(context), child: const Text('Annuler')), const SizedBox(width: 10), ElevatedButton.icon(onPressed: widget.isSubmitting ? null : _submit, icon: widget.isSubmitting ? const SizedBox(width: 16, height: 16, child: CircularProgressIndicator(strokeWidth: 2)) : Icon(_isEdit ? Icons.save_outlined : Icons.add), label: Text(_isEdit ? 'Enregistrer' : 'Créer'))]))])); void _submit() { if (!_formKey.currentState!.validate()) return; if (_isEdit) { final c = widget.initialCounter!; Navigator.pop(context, AdminCounterFormResult.update(AdminStationCounterUpdateRequest(code: _changedText(_codeController.text, c.code), label: _changedText(_labelController.text, c.label)))); return; } Navigator.pop(context, AdminCounterFormResult.create(AdminStationCounterCreateRequest(code: _codeController.text, label: _labelController.text))); } String? _changedText(String current, String? initial) { final trimmed = current.trim(); if (trimmed == (initial ?? '').trim()) return null; return trimmed; } }
class _Header extends StatelessWidget { final String title; final VoidCallback? onClose; const _Header({required this.title, required this.onClose}); @override Widget build(BuildContext context) => Container(padding: const EdgeInsets.all(18), color: Colors.white, child: Row(children: [const Icon(Icons.point_of_sale, color: Color(0xFF0F056B)), const SizedBox(width: 12), Expanded(child: Text(title, style: const TextStyle(fontWeight: FontWeight.w900, fontSize: 18))), IconButton(tooltip: 'Fermer', onPressed: onClose, icon: const Icon(Icons.close))])); }
class _TextField extends StatelessWidget { final TextEditingController controller; final String label; final String fieldName; final StructuredApiError? error; final bool requiredField; final bool enabled; const _TextField({required this.controller, required this.label, required this.fieldName, required this.error, this.requiredField = false, this.enabled = true}); @override Widget build(BuildContext context) => TextFormField(controller: controller, enabled: enabled, textInputAction: TextInputAction.next, decoration: InputDecoration(labelText: requiredField ? '$label *' : label, border: const OutlineInputBorder(), errorText: error?.field == fieldName ? error!.userMessage : null), validator: requiredField ? (value) => value == null || value.trim().isEmpty ? '$label est obligatoire.' : null : null); }
